cpuid_test.go
I'm kind of curious what the value of these tests is, as they depend entirely on the processor you run them on and are only reproducible if you run them on the same processor. Maybe there should be a mockCPU? Most of the bit comparisons are also a bit too easy though. Anyway...
=> Fix TSX test information.

cpuid.go, cpuid_test.go
This patch adds support for SGX Launch Control detection. Tested on NUC 7CJY and mock CPUs (`GenuineIntel00906EA_Coffeelake_CPUID.txt` gives it).
=> Add SGX Launch Control

cpuid.go, cpuid_test.go
Iterate through the SGX EPC section subleaves. This can be used to find out the enclave memory size.
The reference for the bit operations is at https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf (page 1-19).
=> SGX EPC memory size detection support

cpuid.go, cpuid_test.go
Detect features:
- AVX512_VBMI2 (Vector Bit Manipulation Instructions, Version 2)
- AVX512_VNNI* (Vector Neural Network Instructions)
- AVX512_VPOPCNTDQ (Vector Population Count Doubleword and Quadword)
- GFNI (Galois Field New Instructions)
- VAES (Vector AES)
- AVX512_BITALG (AVX-512 Bit Algorithms)
- VPCLMULQDQ (Carry-Less Multiplication Quadword)
- AVX512_BF16 (AVX-512 BFLOAT16 Instructions)
- AVX512_VP2INTERSECT (AVX-512 Intersect for D/Q)
* Renames AVX512VNNI to AVX512_VNNI to keep naming in sync with
Linux kernel and Intel Architecture Programming Reference
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> Detect CPUID flag 7 features (AVX512)

cpuid_test.go
There might be cases where an SGX-enabled device hasn't got SGX EPC subleafs. However, if there are such leaves, the total amount of memory must not be 0.
This should fix https://github.com/klauspost/cpuid/issues/36. @klauspost, can you verify?
=> Fix SGX EPC memory tests.

cpuid.go, cpuid_test.go, mockcpu_test.go
It turns out that you can, sort of, get CPU frequency information
from leaf 0x15, if that's present. If it's not present, you can
parse the information out of the brand string -- Intel actually
documented this as the Official Correct Way to get CPU speed
for quite a while, complete with elaborate parsing logic.
Example:
https://www.scss.tcd.ie/~jones/CS4021/processor-identification-cpuid-instruction-note.pdf
This patch tries to use leaf 0x15 if it's present, which may not
be the wisest choice -- there's rumors of it being buggy on some
parts, but I don't know details. If it's not present, or it would
produce 0 or a division by 0 error, we try the brand string.
If we fail, we yield -1. Running this against the mock CPU tests
revealed what look like reasonably plausible values.
=> add clock frequency determination

cpuid.go, private/cpuid.go, private/cpuid_test.go
Detect L3 cache size on AMD.
Detect hyperthreading on AMD.
Changes:
```diff
813c813
<     TestMocks: mockcpu_test.go:191: L3 Cache: -1 bytes
---
>     TestMocks: mockcpu_test.go:191: L3 Cache: 8388608 bytes
827c827
<     TestMocks: mockcpu_test.go:191: L3 Cache: -1 bytes
---
>     TestMocks: mockcpu_test.go:191: L3 Cache: 8388608 bytes
841c841
<     TestMocks: mockcpu_test.go:191: L3 Cache: -1 bytes
---
>     TestMocks: mockcpu_test.go:191: L3 Cache: 8388608 bytes
855c855
<     TestMocks: mockcpu_test.go:191: L3 Cache: -1 bytes
---
>     TestMocks: mockcpu_test.go:191: L3 Cache: 6291456 bytes
869c869
<     TestMocks: mockcpu_test.go:191: L3 Cache: -1 bytes
---
>     TestMocks: mockcpu_test.go:191: L3 Cache: 8388608 bytes
1065c1065
<     TestMocks: mockcpu_test.go:191: L3 Cache: -1 bytes …
```
=> AMD Updates

detect_intel.go, private/cpuid_detect_intel.go
It looks like `!noasm` tag in `detect_intel.go` only works for amd64. This PR adds `!noasm` for 386, too.
=> Fixed missing noasm tags

README.md, cpuid.go, cpuid_test.go, detect_intel.go
- CPUInfo.Features has run out of space. Therefore following features
are added under separate feature flags (CPUInfo.AmxFeatures), as
discussed in Issue #55.
- AMXBF16 - Tile computational operations on BFLOAT16 numbers
- AMXTILE - Tile architecture
- AMXINT8 - Tile computational operations on 8-bit integers
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> Add CPUInfo.AmxFeatures, detect AMXBF16, AMXTILE and AMXINT8

README.md, cpuid.go, cpuid_test.go, detect_intel.go, mockcpu_test.go
This change deprecates CPU.Features due to a limitation of only
64 feature bits available when using Flags type (uint64).
The new method introduces a FlagSet with flag names as map keys. The set
values are empty structs which, in Go, consume zero bytes.
The proposal is to start adding post-Icelake new features to FlagSet.
The new model makes it possible to combine Arm Flags too (`flagNames` and `flagNamesArm`
are no longer needed)
TODO: more testing and discussion
/cc @askervin
=> Move x86 CPU features from Flags to a FlagSet

cpuid.go
Martin Moehrmann:
> As I learned recently FMA only really requires OSXSAVE as per intel manual.
> so while uncommon someone might use FMA with sse registers on machine with no AVX or support to store and restore YMM registers.
> also know as users still using windows vista kernels
=> Support FMA3 without AVX

cpuid.go, detect_arm64.go, featureid_string.go, os_linux_arm64.go, os_other_arm64.go
Use `sched_getaffinity` to get a logical/physical core count.
This is of course not completely reliable, but is better than nothing.
Trust ARMCPUID and try to get some more information, like vendor, etc.
=> Detect ARM64 affinity cores

.travis.yml, os_darwin_arm64.go, os_linux_arm64.go, os_other_arm64.go, os_safe_linux_arm64.go, os_unsafe_linux_arm64.go
Unsafe is not needed since buffer size is constant.
=> Remove unsafe

detect_arm64.go, detect_ref.go, detect_x86.go, os_other_arm64.go, os_safe_linux_arm64.go, os_unsafe_linux_arm64.go
Starting with Go 1.17, `//go:build` lines are preferred over `// +build`
lines, see https://golang.org/doc/go1.17#build-lines and
https://golang.org/design/draft-gobuild for details.
This change was generated by running Go 1.17 `gofmt` which automatically
adds `//go:build` lines based on the existing `// +build` lines.
=> Add //go:build lines

cmd/cpuid/main.go
Example: `cpuid -check-level=4`
=> Add CPU level test

cpuid.go
Xen Hypervisor is buggy and returns the same entry no matter ECX value.
Hack: When we encounter the same entry 100 times we break.
Fixes #103
=> Fix AMD cache hang on buggy Xen hypervisor

go.mod, go.sum, os_darwin_arm64.go
Here is my try to fill CPUInfo from sysctl on darwin/arm64 when available.
on my laptop:
```
./cpuid -json
{
"BrandName": "Apple M1 Pro",
"VendorID": 0,
"VendorString": "Apple",
"PhysicalCores": 10,
"ThreadsPerCore": 1,
"LogicalCores": 10,
"Family": 458787763,
"Model": 16777228,
"CacheLine": 128,
"Hz": 0,
"BoostFreq": 0,
"Cache": {
"L1I": 131072,
"L1D": 131072,
"L2": 4194304,
"L3": -1
},
"SGX": {
"Available": false,
"LaunchControl": false,
"SGX1Supported": false,
"SGX2Supported": false,
"MaxEnclaveSizeNot64": 0,
"MaxEnclaveSize64": 0,
"EPCSections": null
},
"Features": [
"AESARM",
"ASIMD",
"ASIMDDP",
"ASIMDHP",
"ASIMDRDM",
"ATOMICS",
"CRC32",
"DCPOP",
"FCMA",
"FP",
"FPHP",
"GPA",
"JSCVT",
"LRCPC",
"PMULL",
"SHA1",
"SHA2",
"SHA3",
"SHA512"
],
"X64Level": 0
}
```
data is from:
```
$ sysctl …
```
=> Try to fill darwin arm64 from sysctl

cpuid.go
GFNI, VAES and VPCLMULQDQ does not require AVX512, so detect them even if avx512 isn't available.
=> Relax detection of features that have non-avx512 versions

cpuid.go
MMXEXT is defined in https://github.com/klauspost/cpuid/blob/45f166130b70caa073e0434192b876263c97f47d/cpuid.go#L1188
The removed line corresponds to `ACPI`  according to https://en.wikipedia.org/wiki/CPUID#EAX=1:_Processor_Info_and_Feature_Bits
=> Fixes MMXEXT

README.md, cpuid.go, cpuid_test.go
Small change, change `Has` to pointer receiver.
=> Add CombineFeatures for faster lookups.

cpuid.go
SYSEE or SYSCALL must be present for microarch level.
Fixes old Intel CPUs having level 0.
=> Fix microarch level

.github/workflows/go.yml, .github/workflows/release.yml
Basically, let's ensure we're testing against supported stable versions of golang, and that the actions being used are up-to-date to their latest release.
=> workflows: Update actions and golang versions used

cmd/cpuid/main.go, cpuid.go, cpuid_test.go, detect_x86.go
This patch detects additional information of the AMD Memory Encryption feature.
[0]:
https://www.amd.com/content/dam/amd/en/documents/processor-tech-docs/programmer-references/24594.pdf table E.4.17
=> Add AMD Memory Encrypt detection

cpuid.go, detect_x86.go, featureid_string.go, mockcpu_test.go
Reads the hypervisor vendor as per https://lwn.net/Articles/301888/ and adds it to the `CPUInfo` struct. 
Also fixes the vendor mapping for `KVM`.
=> Add Hypervisor Vendor 

cpuid.go
Hello @klauspost, thanks for the library! I tried running it on my CPU **Ryzen 5 4500u (Zen2)** and found that the number of threads per core (2) and physical cores (3) were incorrect and the HTT option was also detected incorrectly. In fact this cpu has 1 thread per core and 6 physical (and logical) cores
I wrote a fix using the [PPR for AMD Family 17h Models 00h-0Fh Processors](https://github.com/tpn/pdfs/blob/master/AMD%20-%20Preliminary%20Processor%20Programming%20Reference%20(PPR)%20for%20AMD%20Family%2017h%20Models%2000h-0Fh%20Processors%20-%20Rev%201.14%20-%20April%2015th%2C%202017%20(54945).pdf) (page 82)
You can find CPUID dump of **Ryzen 5 4500u** [here](http://users.atw.hu/instlatx64/AuthenticAMD/AuthenticAMD0860F01_K17_Renoir_CPUID3.txt)
=> Fix threadsPerCore check for Zen 2 (AMD)

cpuid.go, os_darwin_arm64.go
```
Detection of Advanced SIMD (NEON) on M1 Macs was broken due to querying
the wrong sysctl identifier. Apple's documentation lists
"hw.optional.AdvSIMD" as the correct identifier, but in reality, it's
"hw.optional.arm.AdvSIMD" as confirmed by `sysctl -a`. This patch
corrects the identifier and adds support for its alias, "hw.optional
.neon," ensuring proper detection across all models.
Additionally, this patch revisits all ARM features detected by the
package, cross-referencing identifiers (and aliases) against both
Apple's official sysctl documentation:
  https://developer.apple.com/documentation/kernel/1387446-sysctlbyname/determining_instruction_set_characteristics
and the ARM architecture reference manual:
  https://developer.arm.com/documentation/ddi0487/latest
Each ARM feature now …
```
=> darwin/arm64: fix SIMD detection and improve ARM feature probing
